### ISSUE TITLE
Is "use strict" missing?

### ISSUE THREAD

**Issue by nathan-yuen** [happylynx/flow-webpack-plugin#1]
```
.../flow-webpack-plugin/dist/index.js:24
    let errorToReport = undefined
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

So it works fine if I manually add `use strict`, is there way around this?

Thanks!

**Comment by happylynx** [comment]
Hi Nathan,
can you please provide output of `node --version`, `npm ls flow-webpack-plugin` and `npm ls webpack` (or `npm ls -g webpack` if you are using global instalation of webpack) executed on failing setup?

**Comment by happylynx** [comment]
Closing. If it happen again, please provide aforementioned details to reopen.
